import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Nav from '@/components/nav';
import SearchPost from '@/components/search';
import Footer from '@/components/footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <html lang='en'>
         <body className={inter.className}>
            <Nav />
            {/* mobile search */}
            <main className='p-3 max-w-5xl mx-auto mt-16 md:mt-20 min-h-screen'>
               <SearchPost isMobile={true} />
               {children}
            </main>
            <Footer />
         </body>
      </html>
   );
}
